### ISSUE TITLE
Cipherlab library

### ISSUE THREAD

**Issue by mdczaplicki** [mribbons/cordova-plugin-cipherlab-rs30#11]
Hi, where did you find cipherlab library?
Did you find any documentation as well?

I want to use it natively in Java, but ReaderManager.InitInstance(this) does return null and I can't get past this.

Best Regards

**Comment by mribbons** [comment]
Hi @mdczaplicki,
The library and sample code are available from your Cipherlab supplier.

**Comment by mdczaplicki** [comment]
Is it possible that you share a documentation with me? A device is a second hand I do not know who was primary supplier. For example through e-mail.

**Comment by mribbons** [comment]
hi @mdczaplicki,
Why buy a second hand device with no documentation? If you are interested as a developer then I suggest you contact your local Cipherlab distributor.

**Comment by mdczaplicki** [comment]
Ufortunately the device is all I've received. There is no official local distributor, only sellers. I will try to contact them then. :)

**Comment by mdczaplicki** [comment]
If someone else is struggling with the same problem as I, here's documentation in Japanese, but it has full example in SoftScan section.
http://www.aimex.co.jp/support/download/pdf/manual/RS30_Androidprogram.pdf
