### ISSUE TITLE
Using this plugin with another device

### ISSUE THREAD

**Issue by tuans** [mribbons/cordova-plugin-cipherlab-rs30#2]
i don't have Cipherlab RS30.
When my application start, i'm press scan button but nothing happened.
I try debug in file CipherlabRS30Plugin.java 
mReaderManager = ReaderManager.InitInstance(cordova.getActivity());
then:
mReaderManager  is null.

Can anyone help me?

**Comment by mribbons** [comment]
Hi there,
What kind of device are you working with?

Does it have a built in scanner or just a regular phone/tablet?

**Comment by tuans** [comment]
I'm using oppo R8001

**Comment by tuans** [comment]
it is just a regular phone
