### ISSUE TITLE
Api.js

### ISSUE THREAD

**Issue by cissemy** [mribbons/cordova-plugin-cipherlab-rs30#9]
Hi,
I am trying to add the plugin : 
cordova plugin add https://github.com/mribbons/cordova-plugin-cipherlab-rs30

But i am getting the error : Your barcodeScanner platform does not have Api.js
Thanks

**Comment by mribbons** [comment]
Hi @cissemy,
Please copy and paste the full error message including the stack trace and the full set of steps to reproduce the error, right from creating your cordova app.

Also please include the output from these:

```sh
cordova --version
cordova platform version android
```

**Comment by mribbons** [comment]
Closing issue, I suspect it is a general cordova issue not specific to this module.
